default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: appname_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: appname_test

production:
  <<: *default
  database: appname_test
